export const WIRES_TASK_ID = '1';
export const O2_CANISTERS_TASK_ID = '2';
export const ALIGN_TELESCOPE_TASK_ID = '3';
export const ASSEMBLE_THE_ARTIFACT_TASK_ID = '4';
export const BUY_BEVERAGE_TASK_ID = '5';
export const MEDBAY_SCAN_TASK_ID = '6';
export const MAZE_TASK_ID = '7';
export const CHART_COURSE_TASK_ID = '8';
export const CLEAN_O2_FILTER_TASK_ID = '9';
export const DECONTAMINATE_TASK_ID = '10';
export const ENTER_ID_CODE_TASK_ID = '11';
export const FUEL_ENGINES_TASK_ID = '12';
export const MEASURE_WEATHER_TASK_ID = '13';
export const PRIME_SHIELDS_TASK_ID = '14';
export const PROCESS_DATA_TASK_ID = '15';
export const RECORD_TEMPERATURE_TASK_ID = '16';
export const SORT_SAMPLES_TASK_ID = '17';
export const START_FANS_TASK_ID = '18';
export const PADLOCK_TASK_ID = '19';
export const MONITOR_TREE_TASK_ID = '20';

export const TASK_IDS = [
    WIRES_TASK_ID,
    O2_CANISTERS_TASK_ID,
    ALIGN_TELESCOPE_TASK_ID,
    ASSEMBLE_THE_ARTIFACT_TASK_ID,
    BUY_BEVERAGE_TASK_ID,
    MEDBAY_SCAN_TASK_ID,
    MAZE_TASK_ID,
    CHART_COURSE_TASK_ID,
    CLEAN_O2_FILTER_TASK_ID,
    DECONTAMINATE_TASK_ID,
    ENTER_ID_CODE_TASK_ID,
    FUEL_ENGINES_TASK_ID,
    MEASURE_WEATHER_TASK_ID,
    PRIME_SHIELDS_TASK_ID,
    PROCESS_DATA_TASK_ID,
    RECORD_TEMPERATURE_TASK_ID,
    SORT_SAMPLES_TASK_ID,
    START_FANS_TASK_ID,
    PADLOCK_TASK_ID,
    MONITOR_TREE_TASK_ID,
];
